// <auto-generated />
using System;
using Finance.Tracking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finance.Tracking.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20250829200612_TotalMarketValue")]
    partial class TotalMarketValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("TotalMarketValue", b =>
                {
                    b.Property<DateOnly>("AsOf")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MarketValue")
                        .HasColumnType("REAL");

                    b.HasKey("AsOf", "Type");

                    b.ToTable("TotalMarketValues");
                });
#pragma warning restore 612, 618
        }
    }
}
